### ISSUE TITLE
Falsche Buchstaben werden beleuchtet

### ISSUE THREAD

**Issue by Nikos410** [piapiekarek/WortUhr#7]
Bei der Wortuhr werden manchmal falsche Buchstaben, zusätzlich zu den für die Zeitanzeige benötigten, beleuchtet. Der Fehler tritt spontan, ohne dass die Uhr bewegt wird, in unregelmäßigen Zeitabständen auf. https://i.imgur.com/IaSUqcK.jpg

**Comment by piapia1991** [comment]
kannst du die Uhr Donnerstags ab 14Uhr  nochmal mitbringen? Dann koennen wir uns das genauer anschauen :)

**Comment by Nikos410** [comment]
Okay, ich komme nach der Arbeit am Donnerstag mal vorbei
